version: "3"

services:
  nuxt:
    build: .
    volumes:
      - ./app:/app
    tty: true
    ports:
      - "3333:3000"
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network
  dynamodb-local:
    container_name: test_dynamodb-local
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - ./dynamodb-local-data:/data
    ports:
      - 8000:8000
    networks:
      - dynamodb-local-network

  dynamodb-admin:
    container_name: test_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network

volumes:
  dynamodb-local-data:

networks:
  dynamodb-local-network:
    driver: bridge
#docker-compose build
###docker-compose run --rm nuxt yarn create nuxt-app
#docker-compose run --rm nuxt npx create-nuxt-app
#docker-compose run --rm nuxt npm install express --save
#docker-compose run --rm nuxt npm install sqlite3 --save
#docker-compose run --rm nuxt npm install aws-sdk --save
#docker-compose run --rm nuxt npm install node-dynamodb-orm --save
#docker-compose run --rm nuxt npm install -g @aws-amplify/cli
#docker-compose run --rm nuxt amplify configure
#aws dynamodb list-tables --endpoint-url http://localhost:8000
#npm install aws-amplify @aws-amplify/ui-vue --dave
#AKIA5CWRFUVRUEPRWWSZ
#VZtGFM4TBMNOmSWAyP+7q/JodpYI1BO8ajONiwyb
#npm 6.14.11
#nod 12.20.1

#/app # npm -v
#6.14.11
#/app # node -v
#v14.15.4
